### ISSUE TITLE
Project fails to build on OSX 10.13.2

### ISSUE THREAD

**Issue by jmfrouin** [voidloop/krakenapi#6]
[09:48:56] jmfrouin@MacBookProWOW:~/p/krakenapi/build (master)$ make
[ 68%] Built target libjson
[ 72%] Building CXX object CMakeFiles/kapi.dir/kraken/kclient.cpp.o
/Users/jmfrouin/p/krakenapi/kraken/kclient.cpp:88:20: error: use of undeclared identifier 'HMAC_CTX_new'; did you mean 'BN_CTX_new'?
   HMAC_CTX *ctx = HMAC_CTX_new();
                   ^~~~~~~~~~~~
                   BN_CTX_new
/usr/local/include/openssl/bn.h:423:9: note: 'BN_CTX_new' declared here
BN_CTX *BN_CTX_new(void);
        ^
/Users/jmfrouin/p/krakenapi/kraken/kclient.cpp:88:14: error: cannot initialize a variable of type 'HMAC_CTX *' (aka 'hmac_ctx_st *') with an rvalue of type 'BN_CTX *' (aka 'bignum_ctx *')
   HMAC_CTX *ctx = HMAC_CTX_new();
             ^     ~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/kapi.dir/kraken/kclient.cpp.o] Error 1
make[1]: *** [CMakeFiles/kapi.dir/all] Error 2
make: *** [all] Error 2

**Comment by nathanielzacharias** [comment]
Refer to https://github.com/voidloop/krakenapi/issues/5 

Also, if you could use the 'insert code' button next to where you see 'AA B i' at the top of the comments box, that would help with the readability of your Terminal output. (I had to click it twice to get it nicely formatted).

**Comment by jmfrouin** [comment]
Oh thanks.
I will do that ! 
Next time in will "insert code" properly, sorry.
